/******************************************************************************************************
// @Public Class:: Claimants Acitivity History Lightning Controller 
// JIRA Task    :: DCR-292 
// SECENARIO    :: POR 4 ,DCR-263
// @Author      :: Subhajit Basak
// Org          :: DFSI-SIRA
*******************************************************************************************************/ 

public class DRS_ClaimantsCommunityService
{
    public static final String INSURER = 'Insurer';
    public static final String CLAIMANT = 'Claimant';
    public static final String NEW_STATUS= 'New';
    public static Boolean BYPASSFLAG = false;
    
}